[package]
name = "iboot-loader"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
binaryninja = { git = "https://github.com/Vector35/binaryninja-api.git"}
log = "0.4.17"
byteorder = "1.4.3"
